name: http-server -> Basic Build
on:
  push:
    paths: 
      - http-server/**
  pull_request:
    paths:
      - http-server/**

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    container: ubuntu:focal
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2.2.0
        with:
          go-version: 1.16
# possibly install necesary pacakges here

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
  
      - name: Build
        run: cd http-server && go build ./...

      # run basic tests for server
      - name: Test
        run: cd http-server/server && go test
      
