name: ci

on:
  push:
    branches: 
      - main
    # consider only http-server dir and/or github workflow dir
    paths: 
      - http-server/**
      - .github/workflows/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: docker hub login
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: docker build & push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/httpserver:latest
          # add cache so that unchanged files are not build again
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/httpserver:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/httpserver:buildcache,mode=max

