name: http-server -> Basic Build
on:
  push:
    paths: 
      - http-server/**
      - .github/workflows/**
  pull_request:
    paths:
      - http-server/**
      - .github/workflows/**

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    container: ubuntu:focal
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
# possibly install necesary pacakges here
      # - name: Set up GCC
        # uses: egor-tensin/setup-gcc@v1
        # with:
          # version: latest
          # platform: x64
# some fun stuff for go
      # - name: Download gcc
      - run: ls -l -R
      - run: which go
      # - run: echo $PATH

      - name: Setup Go
        uses: actions/setup-go@v2.2.0
        with:
          go-version: 1.17
      - name: Build
        working-directory: "./http-server"
        run: go build ./...

      # run basic tests for server
      - name: Test
        working-directory: "./http-server/server"
        run: go test
      
