name: http-server -> Basic Build
on:
  push:
    paths: 
      - http-server/**
  pull_request:
    paths:
      - http-server/**

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    container: ubuntu:focal
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2.2.0
        with:
          go-version: 1.17
# possibly install necesary pacakges here
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
  
      - name: Build
        working-directory: "./http-server"
        run: go build ./...

      # run basic tests for server
      - name: Test
        working-directory: "./http-server/server"
        run: go test
      
